config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/airports/prepare_planes', to: 'airports#prepare_planes'

  get '/airports/planes_on_ready', to: 'airports#planes_on_ready'

  resources :airports, except: [:new, :edit]
  
  


end

app/models/airport.rb
class Airport
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Attributes::Dynamic

  # embeds_many :planes
  # accepts_nested_attributes_for :planes

  has_many :planes, class_name: 'Plane', inverse_of: :airport, autosave: true, dependent: :delete_all
  accepts_nested_attributes_for :planes, allow_destroy: true


  
end

app/models/plane.rb
class Plane
  include Mongoid::Document
  include Mongoid::Timestamps

  belongs_to :airport, :class_name => 'Airport'

  # embedded_in :airport

  field :name, type:String
  field :status, type:String
end

app/models/takeoff_client.rb
require "bunny"
require 'thread'

class TakeoffClient
  attr_accessor :call_id, :response, :lock, :condition, :connection,
                :channel, :server_queue_name, :reply_queue, :exchange

  def initialize
    @connection = Bunny.new(automatically_recover: false)
    @connection.start
    @channel = connection.create_channel
    @exchange = channel.default_exchange
    @server_queue_name = 'airport_queue'

    setup_reply_queue
  end

  def call(plane)
    @call_id = generate_uuid
    p " [x] Requesting take off for plane (#{plane.name})"
    exchange.publish(plane.name,
                     routing_key: server_queue_name,
                     correlation_id: call_id,
                     reply_to: reply_queue.name)

    lock.synchronize { condition.wait(lock) }
    p " [.] #{plane.name} #{response}"
    plane.update(status: response)
    response
  end

  def stop
    channel.close
    connection.close
  end

  private

  def setup_reply_queue
    @lock = Mutex.new
    @condition = ConditionVariable.new
    that = self
    @reply_queue = channel.queue('', exclusive: true)

    reply_queue.subscribe do |_delivery_info, properties, payload|
      if properties[:correlation_id] == that.call_id
        that.response = payload

        # sends the signal to continue the execution of #call
        that.lock.synchronize { that.condition.signal }
      end
    end
  end

  def generate_uuid
    # naive but good enough for the task
    "#{rand}#{rand}#{rand}"
  end
end

app/controllers/airports_controller.rb
class AirportsController < ApplicationController
  before_action :find_airport, only: %i[update taking_off show destroy planes_on_ready]
  after_action :taking_off, only: :update

  def prepare_planes
    number = params[:number].to_i
    planes = []
    @airport = Airport.new
    number.times do |n|
      planes << Plane.create(name: "plane#{n+1}", status: "in the hangar", airport: @airport)
    end
    @airport.planes = planes
    if @airport.save
      redirect_to action: 'planes_on_ready', id: @airport
    end
  end

  def index; end

  def planes_on_ready; end

  def show; end

  def update
    if @airport.update(airport_params)
      render :js => "window.location = '#{airport_path(@airport)}'"
    end
  end

  def destroy
    @airport.destroy
    redirect_to action: 'index'
  end

  private

  def taking_off
    Spawnling.new do
      client = TakeoffClient.new
      @airport.planes.each do |plane|
        client.call(plane)
      end
      client.stop
    end
  end

  def find_airport
    @airport = Airport.find(params[:id])
  end

  def airport_params
    params.require(:airport).permit(planes_attributes: [:id, :name, :status])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/planes_helper.rb
module PlanesHelper
end

app/views/airports/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<%= form_with(url: airports_prepare_planes_path, method: "get", local: true) do %>
  <%= label_tag(:number, "Number of planes:") %>
  <%= text_field_tag(:number) %>
  <%= submit_tag("Ok") %>
<% end %>

</body>
</html>

app/views/airports/planes_on_ready.html.erb
<%= form_for @airport, remote: true do |f| %>
  Planes:
  <ul>
    <%= f.fields_for :planes do |form| %>
      <li>
        <%= form.label :name, form.object.name %>
        <%= form.hidden_field :status, value: "waiting" %>
      </li>
    <% end %>
  </ul>
  <%= f.submit 'Send' %>
<% end %>

app/views/airports/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Airport</title>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script>
      $( document ).ready(setTimeout(function() {
          statuses = document.getElementsByClassName('statuses');
          for (var i = 0; i < statuses.length; ++i) {
              if (statuses[i].textContent != "took off"){
                  location.reload();
              }
          }
          }, 3000)
      );
  </script>
</head>
<body>

<% @airport.planes.each do |plane| %>
<div style="display: inline-block; margin-right: 20px">
  <div><%= plane.name %></div>
  <div class="statuses"><%= plane.status %></div>
</div>
<% end %>

<br>
<br>

<div>
<%= button_to "Restart", airport_path, method: "delete" %>
</div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Airport</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>